---
- hosts: wayf
  remote_user: root
  vars_files:
    - "{{ configdir }}/common_env.yml"
    - "{{ configdir }}/basic_env.yml"
    - "{{ configdir }}/simplesamlphp_env.yml"
    # include the secrets
    - "{{ configdir }}/secrets_env.yml"
  roles:
    - common
    - basic
    - simplesamlphp
