---

### playbook installing the complete SimpleSAMLphp-based WAYF

- hosts: wayf
  remote_user: root
  vars_files:
    - "{{ configdir }}/common_env.yml"
    - "{{ configdir }}/basic_env.yml"
    - "{{ configdir }}/simplesamlphp_env.yml"
    # include the secrets
    - "{{ configdir }}/secrets_env.yml"
  roles:
    - common
    - basic
    - simplesamlphp
  post_tasks:
    # Run the edugain cronjob as a post_tasks block since we first need to
    # finish setting up the full host, which includes running the notified
    # handlers such as httpd.
    - import_tasks: post_tasks/edugain_cronjob.yml
