---
########################################################################
### OVERRIDDEN VALUES FOR THE basic ROLE
########################################################################

### You must define or override the networks parsed as local and the networks
### or hosts trusted for ssh (the latter must be a subset of the former).

#local_nets:
#  - 1.2.3.0/24

#trusted_nets:
#  - 1.2.3.4/32

### same for IPv6
#local_nets_v6:
#  - 1234::/64

#trusted_nets_v6:
#  - 1234::1


### Networks allowed inbound UDP traffic on port 53
#dns_src_nets_v6: "{{ trusted_nets_v6 }}"


### Backup server config: from where are we accessible
#rsync_hosts:
#  - 1.2.3.4/32

#rsync_hosts_v6:
#  - 1234::1


### NTP Server: remote servers
#ntp_servers:
#  - 0.pool.ntp.org
#  - 1.pool.ntp.org


### postfix: smtp_server for relaying email
#smtp_server: smtp.example.org


### HTTP: loglevel and host credentials
#httpd_loglevel: debug

#hostcert: /etc/pki/tls/hostcert.pem
#hostkey: /etc/pki/tls/hostkey.pem
