---
########################################################################
### OVERRIDDEN VALUES FOR THE common ROLE
########################################################################

### PHP

# Set to true to display errors etc.
#phpdebug: true
