---
########################################################################
### OVERRIDDEN VALUES FOR THE simplesamlphp ROLE
########################################################################

### SimpleSAMLphp version
#ssp_version: 1.18.2

### SimpleSAMLphp directory suffix, appended after the version
#ssp_suffix: devel


### Configuration directory for simplesamlphp
#ssp_confdir: "/etc/simplesamlphp/config-{{ ssp_version }}-{{ ssp_suffix }}"

### PKI directory for simplesamlphp
#ssp_pkidir: /etc/pki/simplesamlphp


### Versioned installation directory for SimpleSAMLphp
#ssp_installdir: "{{ ssp_dir }}-{{ ssp_version }}-{{ ssp_suffix }}"

### metadata directory for simplesamlphp
#ssp_metadatadir: "{{ ssp_installdir }}/metadata"

### metadata-generated directory for edugain metadata
#ssp_metadata_generateddir: "{{ ssp_installdir }}/metadata-generated"


### data directory for simplesamlphp
#ssp_datadir: "{{ ssp_installdir }}/data/"


### Some log configuration, more complete setting via config.php

### log directory for simplesamlphp
#ssp_logdir: /var/log/simplesamlphp/

### log level for simplesamlphp. Valid values are
### ERR WARNING NOTICE INFO DEBUG
#ssp_loglevel: "INFO"

### log target for simplesamlphp. Valid values are syslog,file,errorlog,stderr
#ssp_loghandler: "syslog"


### input tarball, you can use the ssp_version inside the name.
### Note that it is currently assumed to be downloaded from a URL, otherwise
### override also ssp_tarball_remote.
#ssp_tarball_remote: true
#ssp_tarball: "https://github.com/simplesamlphp/simplesamlphp/releases/download/v{{ ssp_version }}/simplesamlphp-{{ ssp_version }}.tar.gz"


### tech contact for the service (not metadata), email is address, not href,
### it is used for sending error reports to.
#tech_name: Operator
#tech_email: jdoe@example.org

### timezone: either null or name including single quotes
#timezone: "'Europe/Amsterdam'"


### saml metadata signing certificate and key
### You can create these using e.g.
###  FQDN=<ssp_hostname>
###  openssl req -newkey rsa:3072 -new -x509 -days 3652 -nodes \
###    -out saml-cert-${FQDN}.pem -keyout saml-key-${FQDN}.pem \
###    -subj "/CN=${FQDN}"
#ssp_cert: "saml-cert-{{ ssp_hostname }}.pem"
#ssp_key: "saml-key-{{ ssp_hostname }}.pem"

### eduGAIN metadata signing certificate
#edugain_cert: edugain-metadata-signer.pem

### eduGAIN metadata feed URL
#edugain_url: https://edugain/feed.xml


### idp_remote metadata files to include, split in prod & test
#prod_idp_remotes:
# - idp.example.org.php

#test_idp_remotes:
# - test-idp.example.org.php

### sp_remote metadata files to include, split in prod & test.
### This is typically the Delegation Servers
#prod_sp_remotes:
# - ds.example.org.php

#test_sp_remotes:
# - ds-devel.example.org.php

### entityID
### Can hardcode, but can also use e.g. $ssp_hostname set via {{ ssp_hostname }}
### in ssp_confdir/config_hostname.php or {{ inventory_hostname }}.
#entity_id: "https://$ssp_hostname/{{ ssp_ctx_pfx }}/"

### our own metadata
#meta_org_name: "WAYF"
#meta_org_displayname: "Organization"
#meta_org_url: "https://www.example.org/"

#meta_admin_name: "Operator"
#meta_admin_company: "CA"
#meta_admin_email: "mailto:ca@ca.example.org"

#meta_support_name: "Operator"
#meta_support_company: "CA"
#meta_support_email: "mailto:support@ca.example.org"

#meta_security_name: "CSIRT"
#meta_security_company: "Organization"
#meta_security_email: "mailto:security@example.org"
#meta_security_phone: "+1234567890"

#meta_service_name: "WAYF"
#meta_service_displayname: "Online CA"
#meta_service_description: "Online CA for providing end-user proxy certificates to Science Gateways and other portals"
#meta_service_url: "https://ca.example.org/"
#meta_service_privacy: "https://ca.example.org/privacy"
#meta_service_logo: "https://ca.example.org/images/logo.gif"
#meta_service_logo_small: "https://ca.example.org/images/logo-150.gif"


### Order of the tabs. The mapping to tabs is done via the metadata, and
### typically via config-metarefresh.php for the eduGAIN metadata.
### The actual names of the tabs are determined via the discopower.po files
#tab_order: []
