---
########################################################################
### OVERRIDDEN VALUES FOR THE simplesamlphp ROLE
########################################################################

### SimpleSAMLphp version
#ssp_version: 1.19.8

### SimpleSAMLphp directory suffix, appended after the version
#ssp_suffix: prod


### Configuration directory for simplesamlphp
#ssp_confdir: "/etc/simplesamlphp/config-{{ ssp_version }}-{{ ssp_suffix }}"

### PKI directory for simplesamlphp
#ssp_pkidir: /etc/pki/simplesamlphp


### Versioned installation directory for SimpleSAMLphp
#ssp_installdir: "{{ ssp_dir }}-{{ ssp_version }}-{{ ssp_suffix }}"

### metadata directory for simplesamlphp
#ssp_metadatadir: "{{ ssp_installdir }}/metadata"

### metadata-generated directory for edugain metadata
#ssp_metadata_generateddir: "{{ ssp_installdir }}/metadata-generated"


### data directory for simplesamlphp
#ssp_datadir: "{{ ssp_installdir }}/data/"


### Some log configuration, more complete setting via config.php

### log directory for simplesamlphp
#ssp_logdir: /var/log/simplesamlphp/

### log level for simplesamlphp. Valid values are
### ERR WARNING NOTICE INFO DEBUG
#ssp_loglevel: "INFO"

### log target for simplesamlphp. Valid values are syslog,file,errorlog,stderr
#ssp_loghandler: "syslog"


### input tarball, you can use the ssp_version inside the name.
### Note that it is currently assumed to be downloaded from a URL, otherwise
### override also ssp_tarball_remote.
#ssp_tarball_remote: true
#ssp_tarball: "https://github.com/simplesamlphp/simplesamlphp/releases/download/v{{ ssp_version }}/simplesamlphp-{{ ssp_version }}.tar.gz"


### tech contact for the service. It is used both in the metadata and for
### sending error reports to (after stripping the mailto:).
#tech_name: "RCauth Operator"
#tech_email: "mailto:ops-management@rcauth.eu"

### timezone: either null or name including single quotes
#timezone: "'Europe/Amsterdam'"


### saml metadata signing certificate and key
### You can create these using e.g.
###  FQDN=<ssp_hostname>
###  openssl req -newkey rsa:3072 -new -x509 -days 3652 -nodes \
###    -out saml-cert-${FQDN}.pem -keyout saml-key-${FQDN}.pem \
###    -subj "/CN=${FQDN}"
#ssp_cert: "saml-cert-{{ ssp_hostname }}.pem"
#ssp_key: "saml-key-{{ ssp_hostname }}.pem"

### eduGAIN metadata signing certificate
#edugain_cert: SURFconext-metadata-signer.pem

### eduGAIN metadata feed URL
#edugain_url: https://metadata.surfconext.nl/edugain-downstream.xml


### idp_remote metadata files to include, split in prod & test
#prod_idp_remotes:
# - aai.egi.eu.php
# - cua-sso.surfsara.nl.php
# - idp.scc.kit.edu.php
# - login.elixir-czech.org.php

#test_idp_remotes:
# - wayf.rcauth.eu.php
# - sso.nikhef.nl.php

### sp_remote metadata files to include, split in prod & test.
### This is typically the Delegation Servers
#prod_sp_remotes:
# - wasbord.nikhef.nl.php
# - rcauth-delegation.eosc.grnet.gr.php
# - rcauth-db.esc.rl.ac.uk.php

test_sp_remotes:
 - eir.nikhef.nl.php
 - rcauth-demo-delegation.eosc.grnet.gr.php
 - rcauth-db-dev.esc.rl.ac.uk.php

### entityID
### Can hardcode, but can also use e.g. $ssp_hostname set via {{ ssp_hostname }}
### in ssp_confdir/config_hostname.php or {{ inventory_hostname }}.
#entity_id: "https://$ssp_hostname/{{ ssp_ctx_pfx }}/"

### our own metadata
#meta_org_name: "RCauth"
#meta_org_displayname: "RCauth.eu"
#meta_org_url: "https://rcauth.eu/"

#meta_admin_name: "Admin"
#meta_admin_company: "RCauth"
#meta_admin_email: "mailto:admin@rcauth.eu"

#meta_support_name: "Support"
#meta_support_company: "RCauth"
#meta_support_email: "mailto:support@rcauth.eu"

#meta_security_name: "CSIRT"
#meta_security_company: "RCauth"
#meta_security_email: "mailto:security@rcauth.eu"
#meta_security_phone: "+31205925090"

#meta_service_name: "RCauth WAYF"
#meta_service_displayname: "RCauth Pilot Online CA"
#meta_service_description: "RCauth Pilot Online CA for providing end-user proxy certificates to Science Gateways and other portals"
#meta_service_url: "https://rcauth.eu/"
#meta_service_privacy: "https://rcauth.eu/privacy"
#meta_service_logo: "https://rcauth.eu/images/RCauth-eu-logo.gif"
#meta_service_logo_small: "https://rcauth.eu/images/RCauth-eu-logo-150.gif"


### Order of the tabs. The mapping to tabs is done via the metadata, and
### typically via config-metarefresh.php for the eduGAIN metadata.
### The actual names of the tabs are determined via the discopower.po files
#tab_order: []
