---
########################################################################
### OVERRIDDEN VALUES FOR THE simplesamlphp ROLE
########################################################################

### SimpleSAMLPHP version
ssp_version: 1.18.2

### tech contact for the service (not metadata), email is address, not href,
### it is used for sending error reports to.
tech_name: Operator
tech_email: jdoe@example.org

### timezone: either null or name including single quotes
timezone: "'Europe/Amsterdam'"


### eduGAIN metadata signing certificate
edugain_cert: edugain-metadata-signer.pem

### eduGAIN metadata feed URL
edugain_url: https://edugain/feed.xml

### idp_remote metadata files to include, split in prod & test
prod_idp_remotes:
 - idp.example.org.php

test_idp_remotes:
 - test-idp.example.org.php

### sp_remote metadata files to include, i.e. the DSs, split in prod & test
prod_sp_remotes:
 - ds.example.org.php

test_sp_remotes:
 - ds.example.org.php

### entityID
#entity_id: https://{{ inventory_hostname }}/{{ ssp_ctx_pfx }}/

### our own metadata
meta_org_name: "WAYF"
meta_org_displayname: "Organization"
meta_org_url: "https://www.example.org/"

meta_admin_name: "Operator"
meta_admin_company: "CA"
meta_admin_email: "mailto:ca@ca.example.org"

meta_support_name: "Operator"
meta_support_company: "CA"
meta_support_email: "mailto:support@ca.example.org"

meta_security_name: "CSIRT"
meta_security_company: "Organization"
meta_security_email: "mailto:security@example.org"
meta_security_phone: "+1234567890"

meta_service_name: "WAYF"
meta_service_displayname: "Online CA"
meta_service_description: "Online CA for providing end-user proxy certificates to Science Gateways and other portals"
meta_service_url: "https://ca.example.org/"
meta_service_privacy: "https://ca.example.org/privacy"
meta_service_logo: "https://ca.example.org/images/logo.gif"
meta_service_logo_small: "https://ca.example.org/images/logo-150.gif"
