---

### Definition of several lists, not intended to be overridden

# List of general packages
general_packages:
  # essential for our services
  - tar
  - patch
  - chrony
  - postfix
  # useful:
  - vim-enhanced
  - mailx
  - bind-utils

# List of packages specific for SimpleSAMLphp installation
extra_packages:
  - httpd
  - mod_ssl
  - php
  - php-mbstring
  - php-dom
  - php-json
  # composer related packages:
  - php-pecl-zip
  - git

# List of enabled services
enabled_services:
  - nftables
  - chronyd
  - postfix
  - httpd

# List of disabled services
disabled_services:
  - firewalld
