---

### Task setting up all the config files for SimpleSAMLphp

- name: create configuration directory
  file:
    state: directory
    path: "{{ ssp_confdir }}"
    owner: root
    group: root
    
# Create symlink in the ssp_installdir to the configuration directory
- name: create symlink to config dir
  file:
    state: link
    src: "{{ ssp_confdir }}"
    path: "{{ ssp_installdir }}/config"

- name: create hostname config file
  template:
    src: "config_hostname.php.j2"
    dest: "{{ ssp_confdir }}/config_hostname.php"
    backup: true

# First copy the original config files into a temporary directory

- name: create config tempdir
  tempfile:
    state: directory
    suffix: .config
  register: configtmp

- name: copy configuration templates
  copy:
    remote_src: true
    src: "{{ ssp_installdir }}/{{ item }}"
    dest: "{{ configtmp.path}}/"
  with_items:
    - config.dist/authsources.php.dist
    - config.dist/config.php.dist
    - modules/cron/config/module_cron.php.dist
    - modules/metarefresh/config-templates/module_metarefresh.php
    - modules/discopower/config-templates/module_discopower.php

- name: rename .dist configuration templates
  command:
    cmd: mv "{{ item }}.dist" "{{ item }}"
    chdir: "{{ configtmp.path}}/"
  with_items:
    - authsources.php
    - config.php
    - module_cron.php

- name: copy configuration templated patches
  template:
    src: "config_patch/{{ item }}.j2"
    dest: "{{ configtmp.path }}/{{ item }}"
  with_items:
    - config_authsources.php.patch
    - config_config.php.patch
    - config_module_metarefresh.php.patch
    - config_module_cron.php.patch
    - config_module_discopower.php.patch

- name: patch templated input configuration templates
  patch:
    remote_src: true
    src: "{{ configtmp.path }}/{{ item }}"
    basedir: "{{ configtmp.path }}"
    strip: 2
  with_items:
    - config_authsources.php.patch
    - config_config.php.patch
    - config_module_metarefresh.php.patch
    - config_module_cron.php.patch
    - config_module_discopower.php.patch

- name: copy config files
  copy:
    remote_src: true
    src: "{{ configtmp.path }}/{{ item }}"
    dest: "{{ ssp_confdir }}"
    backup: true
  with_items:
    - authsources.php
    - config.php
    - module_metarefresh.php
    - module_cron.php
    - module_discopower.php

- name: remove config tempdir
  file:
    path: "{{ configtmp.path }}"
    state: absent
