---

### Main task calling all the SimpleSAMLphp related tasks

# Install the main tarball, create symlinks and directories. Then apply the
# source patches and install our rcauth module.
- import_tasks: tarball.yml
- import_tasks: patches.yml
- import_tasks: rcauth_module.yml
- import_tasks: message_catalog.yml

# Setup the config files and disable/enable the modules
- import_tasks: config.yml

# Setup all the metadata related configuration
- import_tasks: saml20_config.yml
- import_tasks: metadata_creds.yml
- import_tasks: metadata.yml

# Now that we're all done create the 'master' symlink
- import_tasks: master_symlink.yml
