---

### Task installing the IdP and SP metadata files

# Create the IdP-remote metadata files from upstream + our patches

- name: create metadata tempdir
  tempfile:
    state: directory
    suffix: .metadata
  register: metadatatmp

- name: copy input metadata
  copy:
    src: "metadata/idp-remote/{{ item }}.orig"
    dest: "{{ metadatatmp.path }}/{{ item }}"
  with_flattened:
    - "{{ prod_idp_remotes }}"
    - "{{ test_idp_remotes }}"

- name: patch metadata
  patch:
    src: "metadata/idp-remote/{{ item }}.patch"
    basedir: "{{ metadatatmp.path }}"
  with_flattened:
    - "{{ prod_idp_remotes }}"
    - "{{ test_idp_remotes }}"

# Copy over our patched IdP-remote metadata files

- name: copy idp-remote metadata
  copy:
    remote_src: true
    src: "{{ metadatatmp.path }}/{{ item }}"
    dest: "{{ ssp_metadatadir }}/idp-remote/"
    backup: true
  with_flattened:
    - "{{ prod_idp_remotes }}"
    - "{{ test_idp_remotes }}"

# Remove the metadata tempdir

- name: remove metadata tempdir
  file:
    path: "{{ metadatatmp.path }}"
    state: absent

# Copy over the sp-remote metadata files

- name: copy sp-remote metadata
  copy:
    src: "metadata/sp-remote/{{ item }}"
    dest: "{{ ssp_metadatadir }}/sp-remote/"
    backup: true
  with_flattened:
    - "{{ prod_sp_remotes }}"
    - "{{ test_sp_remotes }}"

# Setup edugain metadata configuration

- name: create metadata-generated directory
  file:
    path: "{{ ssp_metadata_generateddir }}"
    state: directory
    owner: root
    group: "{{ ssp_group }}"
    mode: 0775

- name: create metadata-generated symlink
  file:
    path: "{{ ssp_metadatadir }}/metadata-generated"
    src: "{{ ssp_metadata_generateddir }}"
    state: link

- name: add cronjob for edugain refresh
  template:
    src: edugain-refresh.j2
    dest: /etc/cron.daily/edugain-refresh
    owner: root
    group: root
    mode: 0755

- name: check edugain metadata is present
  stat:
    path: "{{ ssp_metadata_generateddir }}/edugain/saml20-idp-remote.php"
  register: edugain_stat

# Run cronjob when edugain metadata is absent or older than 24 hours

- name: run edugain cronjob
  command: /etc/cron.daily/edugain-refresh
  when: edugain_stat.stat.exists == False or
        (ansible_date_time.epoch|int - edugain_stat.stat.mtime) > 86400
