---

### Task enabling/disabling modules, see roles/simplesamlphp/vars/main.yml

- name: enable modules
  file:
    path: "{{ ssp_installdir }}/modules/{{ item }}/enable"
    state: touch
  with_items: "{{ enabled_modules }}"

- name: disable modules
  file:
    path: "{{ ssp_installdir }}/modules/{{ item }}/disable"
    state: touch
  with_items: "{{ disabled_modules }}"
