---

- name: enable modules
  file:
    path: "{{ ssp_dir }}/modules/{{ item }}/enable"
    state: touch
  with_items:
    - discopower
    - cron
    - metarefresh

- name: disable modules
  file:
    path: "{{ ssp_dir }}/modules/{{ item }}/disable"
    state: touch
  with_items:
    - consentAdmin
    - memcacheMonitor
    - statistics
    - oauth
    - riak
