---

### Task patching upstream source code, see roles/simplesamlphp/vars/main.yml 

- name: apply code patches
  patch:
    src: "patch/{{ item }}"
    basedir: "{{ ssp_installdir }}"
    strip: 1
    backup: false
  with_items: "{{ source_patches }}"
