---

# First copy the original saml20-*p-*.php config files into a temp directory
# The list of files is defined in vars/main.yml as {{ saml20_items }}.

- name: create saml20 config tempdir
  tempfile:
    state: directory
    suffix: .saml20
  register: saml20tmp

- name: copy saml20 config templates
  copy:
    remote_src: true
    src: "{{ ssp_dir }}/metadata-templates/{{ item }}"
    dest: "{{ saml20tmp.path}}/"
  with_items: "{{ saml20_items }}"

- name: copy saml20 config templated patches
  template:
    src: "saml20_patch/{{ item }}.patch.j2"
    dest: "{{ saml20tmp.path }}/{{ item }}.patch"
  with_items: "{{ saml20_items }}"

- name: patch input saml20 config templates
  patch:
    remote_src: true
    src: "{{ saml20tmp.path }}/{{ item }}.patch"
    basedir: "{{ saml20tmp.path }}"
    strip: 2
  with_items: "{{ saml20_items }}"

- name: copy saml20 config files
  copy:
    remote_src: true
    src: "{{ saml20tmp.path }}/{{ item }}"
    dest: "{{ ssp_metadatadir }}"
    backup: true
  with_items: "{{ saml20_items }}"

- name: remove saml20 config tempdir
  file:
    path: "{{ saml20tmp.path }}"
    state: absent
