---

### Task installing the upstream tarball, creating symlinks and directories

# We unpack the tarball in two stages: first untar, then rename to add suffix.
# We only unpack the tarball when the -version-suffix directory doesn't yet
# exist.
- name: check whether basedir exists
  stat:
    path: "{{ ssp_installdir }}"
  register: st

- name: unpack distribution tarball
  unarchive:
    remote_src: "{{ ssp_tarball_remote }}"
    src: "{{ ssp_tarball }}"
    dest: "{{ httpd_www_root_dir }}"
    creates: "{{ ssp_dir }}-{{ ssp_version }}"
  when: st.stat.isdir is not defined

# Note that we could use creates: but since we've already run stat, a when: is
# more efficient
- name: rename basedir
  command:
    argv:
      - /usr/bin/mv
      - -T
      - "{{ ssp_dir }}-{{ ssp_version }}"
      - "{{ ssp_installdir }}"
  when: st.stat.isdir is not defined

# Setup the configuration directory: rename shipped, real will be made as
# symlink in the config.yml task, once we have the physical directory
- name: rename config directory
  command:
    creates: "{{ ssp_installdir }}/config.dist"
    argv:
      - /usr/bin/mv
      - "{{ ssp_installdir }}/config"
      - "{{ ssp_installdir }}/config.dist"

# Cache directory: needs to exist always for version>=2.2
- name: create cache directory
  file:
    path: "{{ ssp_cachedir }}"
    state: directory
    owner: root
    group: "{{ ssp_group }}"
    mode: 0770

# Logging directory: needs to exist always for version>=2
- name: create logging directory
  file:
    path: "{{ ssp_logdir }}"
    state: directory
    owner: root
    group: "{{ ssp_group }}"
    mode: 0770
