---

# We unpack the tarball in two stages: first untar, then rename to add suffix.
# We should only unpack the tarball when the -version-suffix directory doesn't
# yet exist.
- name: check whether basedir exists
  stat:
    path: "{{ ssp_dir }}-{{ ssp_version }}-{{ ssp_suffix }}"
  register: st

- name: unpack distribution tarball
  unarchive:
    remote_src: "{{ ssp_tarball_remote }}"
    src: "{{ ssp_tarball }}"
    dest: /var
    creates: "{{ ssp_dir }}-{{ ssp_version }}"
  when: st.stat.isdir is not defined

# Note that we could use creates: but since we've already run stat, a when: is
# more efficient
- name: rename basedir
  command:
    argv:
      - /usr/bin/mv
      - "{{ ssp_dir }}-{{ ssp_version }}"
      - "{{ ssp_dir }}-{{ ssp_version }}-{{ ssp_suffix }}"
  when: st.stat.isdir is not defined

- name: make main symlink
  file:
    state: link
    src: "simplesamlphp-{{ ssp_version }}-{{ ssp_suffix }}"
    path: "{{ ssp_dir }}"

# Config directory
- name: rename config directory
  command:
    creates: "{{ ssp_dir }}/config.dist"
    argv:
      - /usr/bin/mv
      - "{{ ssp_dir }}/config"
      - "{{ ssp_dir }}/config.dist"

- name: create symlink to config dir
  file:
    state: link
    src: "{{ ssp_confdir }}"
    path: "{{ ssp_dir }}/config"

# Logging directory: create only when logging to file is enabled
- name: create logging directory
  file:
    path: "{{ ssp_logdir }}"
    state: directory
    owner: root
    group: "{{ ssp_group }}"
    mode: 0770
  when: ssp_loghandler == "file"
