---

### Definition of several lists, not intended to be overridden

# SimpleSAMLphp modules to be explicitly enabled or disabled
enabled_modules:
  - discopower
  - cron
  - metarefresh

disabled_modules:

# List if source patches, applied by task patches.yml
source_patches:
  - frontpage_config.php.patch
  - frontpage_federation.twig.patch
  - _frontpage_menu.twig.patch
  - PowerIdPDisco.php.patch
  - disco.twig.patch
  - en_discopower.po.patch
  - nl_discopower.po.patch
  - MetaLoader.php.patch
  - MetaLoader.php_tagmapping.patch
  - fetch.php.patch
  - hook_cron.php.patch
  - Cron.php.patch
  - croninfo.twig.patch
  - contrab.patch

# List of metadata/* files, installed and configured by task saml20_config.yml
saml20_items:
  - saml20-idp-hosted.php
  - saml20-idp-remote.php
  - saml20-sp-remote.php
