---

### Configure PAM access module, using authselect

- name: add only root user to access.conf file
  blockinfile:
    dest: "/etc/security/access.conf"
    backup: yes
    marker: "# {mark} BASIC ANSIBLE MANAGED BLOCK"
    insertafter: "#- : ALL : ALL"
    block: |
      + : root : LOCAL 127.0.01 ::1 cron crond localhost.localdomain
      + : root :{% for host in trusted_nets %} {{ host }}{% endfor %} # IPv4
      + : root :{% for host in trusted_nets_v6 %} {{ host }}{% endfor %} # IPv6
      - : ALL : ALL
    owner: "root"
    group: "root"
    mode: 0644
  register: pamaccess_config

- name: execute authselect
  command: "authselect select sssd with-pamaccess --force"
  when: pamaccess_config.changed
