---

### Configure NTP using chronyd

# Add our own NTP servers to the config, will be at the EOF
- name: add our ntp servers config
  blockinfile:
    path: /etc/chrony.conf
    marker: "# {mark} LOCAL NTP SERVER"
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
    block: |
      {% for ntp_server in ntp_servers %}
      server {{ ntp_server }}
      {% endfor %}
  notify: restart chronyd

# Since we now have our block at EOF, we can remove existing ones before that
- name: remove existing ntp servers
  replace:
    path: /etc/chrony.conf
    before: "# BEGIN LOCAL NTP SERVER"
    regexp: '^((pool|server) .*)$'
    replace: '#\1'
    owner: "root"
    group: "root"
    mode: 0644
    backup: true
  notify: restart chronyd
  
