---

### Configure Apache httpd

# Copy over host credentials
- name: copy hostcert
  copy:
    src: "{{ inventory_hostname }}.crt"
    dest: "{{ hostcert }}"
    owner: root
    group: root
    mode: 0644
  notify: restart httpd

- name: copy hostkey
  copy:
    src: "{{ inventory_hostname }}.key"
    dest: "{{ hostkey }}"
    owner: root
    group: root
    mode: 0400
  notify: restart httpd

- name: copy intermediate chainfile
  copy:
    src: "{{ inventory_hostname }}.chain"
    dest: "{{ hostcert_intermediate }}"
    owner: root
    group: root
    mode: 0644
  when: hostcert_intermediate is defined
  notify: restart httpd

# Configure site httpd, rest is in /etc/conf.d/ssl.conf etc.

- name: ensure httpd root dir exists
  file:
    path: "{{ httpd_www_root_dir }}"
    state: directory

- name: ensure httpd site config dir exists
  file:
    path: "{{ httpd_www_conf_dir }}"
    state: directory

- name: configure httpd ssl.conf
  template:
    src: ssl.conf.j2
    dest: "{{ httpd_www_conf_dir }}/ssl.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart httpd

- name: configure httpd ciphersuite
  template:
    src: 10-ssl-ciphersuite.conf.j2
    dest: "{{ httpd_www_conf_dir }}/10-ssl-ciphersuite.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart httpd

- name: configure httpd site.conf
  template:
    src: site.conf.j2
    dest: "{{ httpd_www_conf_dir }}/site.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart httpd
