---

### Main task calling all the basic host related tasks

- import_tasks: hostname.yml
- import_tasks: selinux.yml

# lock down ssh access
- import_tasks: sshd.yml
- import_tasks: access.yml

# install packages and update (needs to run before nftables)
- import_tasks: yum.yml

# setup services
- import_tasks: nftables.yml
- import_tasks: chronyd.yml
- import_tasks: postfix.yml

# Setup apache and php
- import_tasks: php.yml
- import_tasks: httpd.yml

# Replace logrotate configurations
- import_tasks: logrotate.yml

# disable services
- name: disable services
  service: name={{ item }} state=stopped enabled=no
  with_items: "{{ disabled_services }}"

# enable services
- name: enable services
  service: name={{ item }} state=started enabled=yes
  with_items: "{{ enabled_services }}"
