---

### Configure PHP settings

- name: increase execution time
  lineinfile:
    path: "/etc/php.ini"
    regexp: 'max_execution_time\s+=.*$'
    insertafter: '^;max_execution_time\s+='
    line: 'max_execution_time = 300'
    backup: yes
  notify: restart php-fpm

- name: increase memory limit
  lineinfile:
    path: "/etc/php.ini"
    regexp: 'memory_limit\s+=.*$'
    insertafter: '^;memory_limit\s+='
    line: 'memory_limit = 1G'
    backup: yes
  notify: restart php-fpm

- name: disable expose_php
  lineinfile:
    path: "/etc/php.ini"
    regexp: '^expose_php\s+=.*$'
    insertafter: '^;expose_php\s+='
    line: "expose_php = Off"
    backup: yes
  notify: restart php-fpm

- name: enable display errors
  lineinfile:
    path: "/etc/php.ini"
    regexp: '^display_errors\s+=.*$'
    insertafter: '^;display_errors\s+='
    line: "display_errors = {{ 'On' if phpdebug else 'Off' }}"
    backup: yes
  notify: restart php-fpm

- name: enable display startup errors
  lineinfile:
    path: "/etc/php.ini"
    regexp: '^display_startup_errors\s+=.*$'
    insertafter: '^;display_startup_errors\s+='
    line: "display_startup_errors = {{ 'On' if phpdebug else 'Off' }}"
    backup: yes
  notify: restart php-fpm
